preload = /home/eugene/Pictures/luna-stream-wall-7680x2160_black.png
splash = false
wallpaper {
    monitor = DP-2
    path = /home/eugene/Pictures/luna-stream-wall-7680x2160_black.png
}

#preload = ~/Pictures/night_beauty_by_magnaluna_dd4qbvm-fullview.jpg
#wallpaper = DP-2, ~/Pictures/night_beauty_by_magnaluna_dd4qbvm-fullview.jpg

