# rebinds
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# window settings
bind c new-window -c "#{pane_current_path}"
bind  %  split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

set-option -g history-limit 5000

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin "arcticicestudio/nord-tmux"

set -g mouse on

run '~/.tmux/plugins/tpm/tpm'

